name: Build and Deploy to GitHub Pages

on:
  workflow_dispatch: 
  schedule:
    - cron: '0 0 * * 1'  # Run every Monday at midnight (UTC)
  push:
    branches:
      - main

permissions:
  contents: write
  pages: write
  id-token: write

jobs:
  build_and_deploy:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v2

    - name: Set up Python
      uses: actions/setup-python@v2
      with:
        python-version: 3.8

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install Jinja2

    - name: Run generate_static.py
      run: |
        python generate_static_site.py

    - name: Add everything in assets folder
      run: |
        cp -r assets/* .

    - name: Upload GitHub Pages artifact
      uses: actions/upload-pages-artifact@v2.0.0
      with:
          # Upload entire repository
          path: '.'
    
    - name: Deploy GitHub Pages site
      id: deployment
      uses: actions/deploy-pages@v2.0.3

